minimum_movement_delay = 0.1
unstuck_movement_delay = 2.4
unstuck_movement_hold_time = 1.4
perceived_tile_size = 54
wall_model_classes = [ "wall", "bush", "close_bush",]
gadget_pixels_minimum = 1300.0
hypercharge_pixels_minimum = 1800.0
super_pixels_minimum = 1800.0
idle_pixels_minimum = 75000.0
centered_wall_detection = false
wall_detection_confidence = 0.5
entity_detection_confidence = 0.65
seconds_to_hold_attack_after_reaching_max = 1.5
play_again_on_win = "no"
current_playstyle = "universal_smart_v5_Slarckvul_Eddition.pyla"
